import { Alert, AlertIcon, Button, Flex, Heading, Input, Link } from '@chakra-ui/react'
import Head from 'next/head'
import { FormEvent, useState } from 'react'
import { shortenUrl } from '../api/url-shortner'
import styles from '../styles/Home.module.css'
import UrlEntiryProps from '../types/url-entity.type'

export default function Home() {

  const [urls, setUrls] = useState<UrlEntiryProps[]>([])
  const [error, setError] = useState<string | null>(null)

  const onSubmitHandler = async (e: FormEvent<HTMLFormElement>) => {
    try {
      e.preventDefault()
      const currentUrl = e.currentTarget.inputLongUrl.value
      const response = await shortenUrl(currentUrl)
      setUrls([...urls, response as UrlEntiryProps])
      setError(null)
    } catch (error: unknown) {
      if (error instanceof Error) {
        setError(error.message)
      }
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <Heading className={styles.title}>
          Welcome to Bit.ly
        </Heading>

        <form onSubmit={onSubmitHandler}>

          {error && <Alert status='error' mt={5}>
            <AlertIcon />
            {error}
          </Alert>}

          <Flex flexDirection={'row'} mt={10}>
            <Input name='inputLongUrl' size={'lg'} w='600px' type="url" required></Input>
            <Button size={'lg'} ml={3} type='submit'>Shorten</Button>
          </Flex>
        </form>



        <Flex mt={10} w='100%' alignItems={'center'} flexDirection={'column'}>
          {urls && urls.map((url: UrlEntiryProps, i: number) => (
            <Flex key={i} justifyContent='space-between' width={'55%'} p={2} >
              <Flex>
                <Link href={url.originalUrl} isExternal>
                  {url.originalUrl}
                </Link>
              </Flex>
              <Flex>
                <Link href={`${process.env.NEXT_PUBLIC_API_URL}/${url.shortUrlKey}`} isExternal>
                  {`${process.env.NEXT_PUBLIC_API_URL}/${url.shortUrlKey}`}
                </Link>
                <Button ml={3} size={'xs'}>Copy</Button>
              </Flex>
            </Flex>))}
        </Flex>
      </main>
    </div >
  )
}
